### ISSUE TITLE
Купить домен

### ISSUE THREAD

**Issue by dronfree** [dronfree/mml#21]

**Comment by devkpv** [comment]
@dronfree Так купи уже! Или надо помочь?)

**Comment by dronfree** [comment]
Так все некогда )

вторник, 9 февраля 2016 г. пользователь SpiLLeR написал:

**Comment by dronfree** [comment]
Купи ты, если собрался до ночи сидеть. 69 рэ на годадди. Нсы в паблике айпи
известен.

вторник, 9 февраля 2016 г. пользователь Alex Dron написал:

**Comment by devkpv** [comment]
Допилю рандомайзер и может куплю или усну))

**Comment by devkpv** [comment]
Купил mmlhub.xyz
DNS 212.47.246.2
