### ISSUE TITLE
Fix for possible loop when generate emails

### ISSUE THREAD

**Issue by devkpv** [dronfree/mml#34]

**Comment by dronfree** [comment]
endless loop?

**Comment by dronfree** [comment]
When I run program this way

``` bash
go run pvbm.go -length=1 -count=100
```

it outputs all possible values and hangs.

**Comment by devkpv** [comment]
Yeap. Fix in pull request.
I added max repeat rate.

**Comment by dronfree** [comment]
Put #34 but not #34: (with semicolon). I merged your pull request but this issue is not closed automatically. Closing it.
